# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Date created')),
                ('latitude', models.DecimalField(
                    decimal_places=20, max_digits=23,
                    verbose_name='Latitude')),
                ('longitude', models.DecimalField(
                    decimal_places=20, max_digits=23,
                    verbose_name='Longitude')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
